[manifest]
version = "0.0.1"
dump_lua = true
priority = 999


[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = 'function Game:update(dt)'
position = 'after'
match_indent = true
payload = '''

if G.GAME.round_resets.blind_choices and G.GAME.round_resets.blind_choices.Boss and (
    G.GAME.defeated_blinds["bl_unik_artisan_builds"] or 
    G.GAME.round_resets.blind_choices.Boss == 'bl_unik_artisan_builds' or
    G.GAME.defeated_blinds["bl_unik_epic_artisan"] or 
    G.GAME.round_resets.blind_choices.Boss == 'bl_unik_epic_artisan' or 
    G.GAME.round_resets.blind_choices.Big == 'bl_unik_epic_artisan' or 
    G.GAME.round_resets.blind_choices.Small == 'bl_unik_epic_artisan' or 
    G.GAME.round_resets.blind_choices.Big == 'bl_unik_artisan_builds' or  
    G.GAME.round_resets.blind_choices.Small == 'bl_unik_artisan_builds'
    ) then
    G.GAME.unik_artisan_reroll_time = true
    
else
    G.GAME.unik_artisan_reroll_time = nil
    G.GAME.ante_rerolls = 0
end
'''

