[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999

### Bigger Blind and Boring Blank functionality to emulate Small and Big Blinds in appearance and functionality, while still ""bosses""
### And also make them ineligable for reroll (but can appear naturally) and not enable chicot/luchador to function

### Bigger blind colors
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif blindname == 'Small Blind' or blindname == 'Big Blind' or blindname == '' then'''
position = "before"
payload = '''
elseif blindname == 'bl_unik_bigger_blind' or blindname == 'bl_unik_boring_blank' then
    ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''elseif G.GAME.won then 
        ease_background_colour{new_colour = G.C.BLIND.won, contrast = 1}'''
position = "after"
payload = '''
elseif blindname == 'bl_unik_bigger_blind' or blindname == 'bl_unik_boring_blank' then
    ease_background_colour{new_colour = G.C.BLIND['Small'], contrast = 1}
'''
match_indent = true

##Ease ante when defeating bigger/boss blinds
[[patches]]
[patches.regex]
target = 'functions/state_events.lua'
pattern = '''G\.GAME\.blind\:get\_type\(\) \=\= \'Boss\''''
position = "at"
line_prepend = '$indent'
payload = '''(G.GAME.blind_on_deck == 'Boss') '''