[manifest]
version = "0.0.1"
dump_lua = true
priority = 999
##Adding my scaling Jokers into BigNum

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "lib/misc.lua"]'''
pattern = '''j_cry_mprime = true,'''
position = "after"
payload = '''
j_unik_extra_credit_alice = true,
j_unik_border_wall = true,
j_unik_jsab_chelsea = true,
j_unik_jsab_yokana = true,
--j_unik_white_lily_cookie = true, --white lily cookie's abilities do not go well with big_num, hence she does not count as bignum
j_unik_moonlight_cookie = true,
j_unik_unik = true,
j_unik_riif_roof = true,
j_unik_ghost_trap = true,
j_unik_recycler = true,
j_unik_noon = true,
j_unik_no_standing_zone = true,
j_unik_gt710 = true,
j_unik_cube_joker = true,
j_unik_mutilated_mess = true,
j_unik_cube_of_calamity = true,
j_unik_celestial_of_chaos = true,
'''
match_indent = true

### White Lily Cookie: Scalae and double scale support:

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "lib/calculate.lua"]'''
pattern = '''if jkr.ability.name == "cry-Exponentia" then'''
position = "before"
payload = '''
if jkr.ability.name == "j_unik_white_lily_cookie" then
    dbl_info.base = { "extra", "Emult" }
    dbl_info.scaler = { "extra", "Emult_mod" }
    dbl_info.scaler_base = jkr.ability.extra.Emult_mod
    dbl_info.offset = 1
end
'''
match_indent = true

