[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "delay(0.5)"
position = "before"
payload = '''
G.jokers.config.highlighted_limit = 1e10
G.consumeables.config.highlighted_limit = 1e10
if not saveTable and G.GAME.modifiers.unik_single_select_limit then
    G.E_MANAGER:add_event(Event({
        trigger = "after",
        delay = 0.7,
        func = function()
            SMODS.change_play_limit(1 - G.GAME.starting_params.play_limit)
            SMODS.change_discard_limit(1 - G.GAME.starting_params.discard_limit)
            G.hand.config.highlighted_limit = 1
            return true
        end,
    }))
    
end
'''
match_indent = true
