[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

# Register banned jokers for Common Muck
# Also initializes disabled/enabled cards
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "set_profile_progress()"
position = "before"
payload = '''
-- adding banned jokers for common muck
for i = 1, #G.CHALLENGES do
    if G.CHALLENGES[i].id == 'c_unik_common_muck' and #G.CHALLENGES[i].restrictions.banned_cards == 0 then
        for k, v in pairs(G.P_CENTERS) do
            -- Check if its a joker
            if v.set == "Joker" then
                --check if its not a common (cursed jokers will still appear, cause Bigger Boo and Purple Pentagram)
                if v.rarity ~= 1 and v.rarity ~= "cry_cursed" then
                    G.CHALLENGES[i].restrictions.banned_cards[#G.CHALLENGES[i].restrictions.banned_cards+1] = {id = k}
                end
            end
        end
        -- Add THE SOUL, wraith, summoning and Gateway to the banned cards
        G.CHALLENGES[i].restrictions.banned_cards[#G.CHALLENGES[i].restrictions.banned_cards+1] = {id = 'c_soul'}
        G.CHALLENGES[i].restrictions.banned_cards[#G.CHALLENGES[i].restrictions.banned_cards+1] = {id = 'c_wraith'}
        G.CHALLENGES[i].restrictions.banned_cards[#G.CHALLENGES[i].restrictions.banned_cards+1] = {id = 'c_cry_gateway'}
        G.CHALLENGES[i].restrictions.banned_cards[#G.CHALLENGES[i].restrictions.banned_cards+1] = {id = 'c_cry_summoning'}
    end
end
'''
match_indent = true

# Force shop to only spawn common jokers
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')"
position = "at"
payload = '''
local card
if v.type == 'Joker' and G.GAME.modifiers.unik_common_only then
    --print("COMMON ONLY!")
    card = create_card(v.type, area, nil, 0, nil, nil, nil, 'sho')
else
    card = create_card(v.type, area, nil, nil, nil, nil, nil, 'sho')
end
'''
match_indent = true

# Force buffoon pack to only spawn common jokers
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''card = create_card("Joker", G.pack_cards, nil, nil, true, true, nil, 'buf')'''
position = "at"
payload = '''
if G.GAME.modifiers.unik_common_only then
    --print("COMMON ONLY!")
    card = create_card("Joker", G.pack_cards, nil, 0, true, true, nil, 'buf')
else
    card = create_card("Joker", G.pack_cards, nil, nil, true, true, nil, 'buf')
end
'''
match_indent = true
