[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999999

## Initializer

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "set_profile_progress()"
position = "before"
payload = '''
--self:unik_initialize_stuff()
'''
match_indent = true