[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999999

## Artificially add abstracted 'suits' to flush calculations without declaring them (sigil, familiar)
## Also make sure to create a hard copy of suits and iterate, otherwise adding the artificial suit will add it to suit.obj_buffer for real!
[[patches]]
[patches.pattern]
target = '''functions/misc_functions.lua'''
pattern = '''local suits = SMODS.Suit.obj_buffer'''
position = "after"
payload = '''
    for i = 1, #G.ENHANCEMENT_OVERRIDE_SUITS do
        suits[#suits + 1] = G.ENHANCEMENT_OVERRIDE_SUITS[i]
    end
'''
match_indent = true

## My mistake, should've made them more compat. Now I have to deal with this.
[[patches]]
[patches.pattern]
target = '''functions/misc_functions.lua'''
pattern = '''local suits = {}'''
position = "after"
payload = '''
    for i = 1, #G.ENHANCEMENT_OVERRIDE_SUITS do
        suits[#suits + 1] = G.ENHANCEMENT_OVERRIDE_SUITS[i]
    end
'''
match_indent = true

## suits
## Artificially add abstracted 'rank' to X of a kind calculations
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''for i=#hand, 1, -1 do'''
position = "before"
payload = '''
    for i = 1, #G.ENHANCEMENT_OVERRIDE_RANKS do
        vals[#vals + 1] = {}
    end
'''
match_indent = true