[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

### Enable the ability to see negative values
[[patches]]
[patches.pattern]
target = '''functions/button_callbacks.lua'''
pattern = '''e.config.object.scale = scale_number(G.GAME.current_round.current_hand.chips, 0.9, 1000)'''
position = "after"
payload = '''
if (to_big(G.GAME.current_round.current_hand.chips) < to_big(0)) then
    print(new_chip_text)
    print(G.GAME.current_round.current_hand.chips)
end
'''
match_indent = true