[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

### Stop more impossible combinations from occurring
### Video Poker =/= Nostalgic Arm, Video Poker =/= Sapphire Stamp, indigo ICBM + the poppy and lavender loop
### 

[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "lib/overrides.lua"]'''
pattern = '''and (self.name ~= "cry-Tax" or not G.GAME.defeated_blinds["bl_needle"])'''
position = "after"
payload = '''
and (self.name ~= "bl_unik_video_poker" or not G.GAME.defeated_blinds["bl_cry_oldarm"])
and (self.name ~= "cry-oldarm" or not G.GAME.defeated_blinds["bl_unik_video_poker"])
and (self.name ~= "bl_unik_video_poker" or not G.GAME.defeated_blinds["bl_serpent"])
and (self.name ~= "The Serpent" or not G.GAME.defeated_blinds["bl_unik_video_poker"])
and (self.name ~= "bl_unik_video_poker" or not G.GAME.defeated_blinds["bl_cry_oldmark"])
and (self.name ~= "cry-oldmark" or not G.GAME.defeated_blinds["bl_unik_video_poker"])
and (self.name ~= "bl_unik_video_poker" or not G.GAME.defeated_blinds["bl_cry_sapphire_stamp"])
and (self.name ~= "cry-Sapphire Stamp" or not G.GAME.defeated_blinds["bl_unik_video_poker"])
and (self.name ~= "cry-Lavender Loop" or not G.GAME.defeated_blinds["bl_unik_poppy"])
and (self.name ~= "bl_unik_poppy" or not G.GAME.defeated_blinds["bl_cry_lavender_loop"])
and (self.name ~= "cry-Lavender Loop" or not G.GAME.defeated_blinds["bl_unik_indigo_icbm"])
and (self.name ~= "bl_unik_indigo_icbm" or not G.GAME.defeated_blinds["bl_cry_lavender_loop"])
'''
match_indent = true