[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

### Multiply: no need for init
[[patches]]
[patches.pattern]
target = '''=[SMODS Cryptid "items/pointer.lua"]'''
pattern = '''Cryptid.pointerblistifytype("rarity", "cry_exotic", nil)'''
position = "after"
payload = '''
if next(SMODS.find_mod("finity")) then
    Cryptid.pointerblistifytype("rarity", "unik_finity_legendary_crown", nil)
end

'''
match_indent = true