[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''if not hidden_suits[visible_suit[i]] then'''
position = "at"
payload = '''if visible_suit[i] and not hidden_suits[visible_suit[i]] then'''
match_indent = true

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''if G.GAME.blind then t[#t + 1] = { object = G.GAME.blind, scored_card = G.GAME.blind.children.animatedSprite } end'''
position = "before"
payload = '''if G.GAME.blind and G.GAME.blind.children and G.GAME.blind.children.animatedSprite and G.GAME.blind.children.animatedSprite then'''
match_indent = true
[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''if G.GAME.blind then t[#t + 1] = { object = G.GAME.blind, scored_card = G.GAME.blind.children.animatedSprite } end'''
position = "after"
payload = '''end'''
match_indent = true