[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''if not hidden_suits[visible_suit[i]] then'''
position = "at"
payload = '''if visible_suit[i] and not hidden_suits[visible_suit[i]] then'''
match_indent = true