[manifest]
version = "0.0.1"
dump_lua = true
priority = 999

###The leak functionality -- disable plasma effect + say "Not Balanced!"

[[patches]]
[patches.pattern]
target = 'back.lua'
pattern = '''if self.name == 'Plasma Deck' and args.context == 'final_scoring_step' then'''
position = 'before'
payload = '''
--The leak functionality: Goes before plasma deck functionality
if self.name == 'Plasma Deck' and args.context == 'final_scoring_step' and G.GAME.unik_disable_catalyst then
G.E_MANAGER:add_event(Event({
    func = (function()
        local text = localize('k_unik_plasma_deck_fail')
        attention_text({
            scale = 1.4, text = text, hold = 2, align = 'cm', offset = {x = 0,y = -2.7},major = G.play
        })
        G.GAME.blind.triggered = true
        G.GAME.blind:wiggle()
        return true
    end)
}))
    delay(0.6)
    return args.chips, args.mult
end
'''
match_indent = true