[manifest]
version = "0.0.1"
dump_lua = true
priority = 9999

### legendary magnet - Trigger player death

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = 'at'
payload = '''
if G.GAME.unik_instant_death_hand then
    G.GAME.chips = 0
    G.E_MANAGER:add_event(
        Event({
            trigger = "immediate",
            func = function()
                if G.STATE ~= G.STATES.SELECTING_HAND then
                    return false
                end
                G.STATE = G.STATES.HAND_PLAYED
                G.STATE_COMPLETE = true
                end_round()
                return true
            end,
        }),
        "other"
    )

else
    play_area_status_text("Not Allowed!")
end
'''
match_indent = true

### scary warning text

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''if not self.boss_warning_text then'''
position = 'at'
payload = '''if not self.boss_warning_text and not G.GAME.unik_instant_death_hand then'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''play_sound('chips1', math.random()*0.1 + 0.55, 0.12)
            end'''
position = 'after'
payload = '''
if not self.boss_warning_text and G.GAME.unik_instant_death_hand then 
                self.boss_warning_text = UIBox{
                    definition = 
                      {n=G.UIT.ROOT, config = {align = 'cm', colour = G.C.CLEAR, padding = 0.2}, nodes={
                        {n=G.UIT.R, config = {align = 'cm', maxw = 1}, nodes={
                            {n=G.UIT.O, config={object = DynaText({scale = 0.7, string = localize('ph_unik_instakill_hand'), maxw = 9, colours = {G.C.UNIK_EYE_SEARING_RED},float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6})}},
                        }},
                        {n=G.UIT.R, config = {align = 'cm', maxw = 1}, nodes={
                            {n=G.UIT.O, config={object = DynaText({scale = 0.6, string = G.GAME.blind:get_loc_debuff_text(), maxw = 9, colours = {G.C.UNIK_EYE_SEARING_RED},float = true, shadow = true, silent = true, pop_in = 0, pop_in_rate = 6})}},
                        }}
                    }}, 
                    config = {
                        align = 'cm',
                        offset ={x=0,y=-3.1}, 
                        major = G.play,
                      }
                  }
                  self.boss_warning_text.attention_text = true
                  self.boss_warning_text.states.collide.can = false
                  G.GAME.blind.children.animatedSprite:juice_up(0.5, 0.2)
                  play_sound('cancel', 0.8, 1)
                  G.ROOM.jiggle = G.ROOM.jiggle + 2
            end
'''
match_indent = true