[manifest]
version = "0.0.1"
dump_lua = true
priority = 999
### fix spectral acclimator

### Always have infinite selection limit in video poker to avoid softlocking.
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{type = 'Spectral', val = G.GAME.spectral_rate},"
position = "at"
payload = "{type = 'Spectral', val = G.GAME.spectral_rate*(G.GAME.cry_percrate.spectral/100)},"
match_indent = true